In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
train_path = "/home/hidehisa/Data/kaggle_toxic_comment/train.csv"
test_path = "/home/hidehisa/Data/kaggle_toxic_comment/test.csv"

with open(train_path, "r") as f:
    df_train = pd.read_csv(f)
    
with open(test_path, "r") as f:
    df_test = pd.read_csv(f)

In [5]:
df_train.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [6]:
df_test.head()

                 id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [7]:
df_train.describe()

,toxic,severe_toxic,obscene,threat,insult,identity_hate
count,159571.000000,159571.000000,159571.000000,159571.000000,159571.000000,159571.000000
mean,0.095844,0.009996,0.052948,0.002996,0.049364,0.008805
std,0.294379,0.099477,0.223931,0.054650,0.216627,0.093420
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df_train["comment_text"]

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
5         "\n\nCongratulations from me as well, use the ...
6              COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK
7         Your vandalism to the Matt Shirvington article...
8         Sorry if the word 'nonsense' was offensive to ...
9         alignment on this subject and which are contra...
10        "\nFair use rationale for Image:Wonju.jpg\n\nT...
11        bbq \n\nbe a man and lets discuss it-maybe ove...
12        Hey... what is it..\n@ | talk .\nWhat is it......
13        Before you start throwing accusations and warn...
14        Oh, and the girl above started her arguments w...
15        "\n\nJuelz Santanas Age\n\nIn 2002, Juelz Sant...
16        Bye! \n\nDon't look, come or think of comming ...
17         REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski
18        The Mitsurugi point made no sense - why not ar...
19        Don't mean to bother you \n\nI see that you're...
20        "\n\n Regarding your recent edits \n\nOnce aga...
21        "\nGood to know. About me, yeah, I'm studying ...
22        "\n\n Snowflakes are NOT always symmetrical! \...
23        "\n\n The Signpost: 24 September 2012 \n\n Rea...
24        "\n\nRe-considering 1st paragraph edit?\nI don...
25        Radial symmetry \n\nSeveral now extinct lineag...
26        There's no need to apologize. A Wikipedia arti...
27        Yes, because the mother of the child in the ca...
28        "\nOk. But it will take a bit of work but I ca...
29        "== A barnstar for you! ==\n\n  The Real Life ...
                                ...
159541    Your absurd edits \n\nYour absurd edits on gre...
159542    maybe he's got better things to do than spend ...
159543    scrap that, it does meet criteria and its gone...
159544                                  You could do worse.
159545    , 7 March 2011 (UTC)\nAre you also User:Bmatts...
159546    "\n\nHey listen don't you ever!!!! Delete my e...
159547                       Thank you very, very much.  ·✆
159548                          Talkback: 15 September 2012
159549                           2005 (UTC)\n 06:35, 31 Mar
159550    i agree/ on another note lil wayne is a talent...
159551    While about half the references are from BYU-I...
159552    Prague Spring \n\nI think that Prague Spring d...
159553    I see this as having been merged; undoing one ...
159554    and i'm going to keep posting the stuff u dele...
159555    "\n\nHow come when you download that MP3 it's ...
159556    I'll be on IRC, too, if you have a more specif...
159557    It is my opinion that that happens to be off-t...
159558    Please stop removing content from Wikipedia; i...
159559    Image:Barack-obama-mother.jpg listed for delet...
159560    "Editing of article without Consensus & Remova...
159561    "\nNo he did not, read it again (I would have ...
159562    "\n Auto guides and the motoring press are not...
159563    "\nplease identify what part of BLP applies be...
159564    Catalan independentism is the social movement ...
159565    The numbers in parentheses are the additional ...
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [9]:
df_test.shape

(153164, 2)

In [23]:
df_train.sum(axis=1).mean()

0.2199522469621673

In [28]:
df_train.iloc[:, 2:]

        toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
5           0             0        0       0       0              0
6           1             1        1       0       1              0
7           0             0        0       0       0              0
8           0             0        0       0       0              0
9           0             0        0       0       0              0
10          0             0        0       0       0              0
11          0             0        0       0       0              0
12          1             0        0       0       0              0
13          0             0        0       0       0              0
14          0             0        0       0       0              0
15          0             0        0       0       0              0
16          1             0        0       0       0              0
17          0             0        0       0       0              0
18          0             0        0       0       0              0
19          0             0        0       0       0              0
20          0             0        0       0       0              0
21          0             0        0       0       0              0
22          0             0        0       0       0              0
23          0             0        0       0       0              0
24          0             0        0       0       0              0
25          0             0        0       0       0              0
26          0             0        0       0       0              0
27          0             0        0       0       0              0
28          0             0        0       0       0              0
29          0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159541      1             0        1       0       1              0
159542      0             0        0       0       0              0
159543      0             0        0       0       0              0
159544      0             0        0       0       0              0
159545      0             0        0       0       0              0
159546      1             0        0       0       1              0
159547      0             0        0       0       0              0
159548      0             0        0       0       0              0
159549      0             0        0       0       0              0
159550      0             0        0       0       0              0
159551      0             0        0       0       0              0
159552      0             0        0       0       0              0
159553      0             0        0       0       0              0
159554      1             0        1       0       1              0
159555      0             0        0       0       0              0
159556      0             0        0       0       0              0
159557      0             0        0       0       0              0
159558      0             0        0       0       0              0
159559      0             0        0       0       0              0
159560      0             0        0       0       0              0
159561      0             0        0       0       0              0
159562      0             0        0       0       0              0
159563      0             0        0       0       0              0
159564      0             0        0       0       0              0
159565      0             0        0       0       0              0
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [17]:
import wordbatch
from wordbatch.models import FM_FTRL, FTRL
from nltk.corpus import stopwords
from wordbatch.extractors import WordBag
import re

In [15]:
stop = {x: 1 for x in stopwords.words('english')}
non_alphanums = re.compile(u'[^A-Za-z0-9]+')


def normalize_text(text):
    return u" ".join(
        [x for x in [y for y in non_alphanums.sub(' ', text).lower().strip().split(" ")] \
         if len(x) > 1 and x not in stop])

In [18]:
wb = wordbatch.WordBatch(normalize_text, extractor=(WordBag, {"hash_ngrams": 2, "hash_ngrams_weights": [1.5, 1.0],
                                                                  "hash_size": 2 ** 22, "norm": None, "tf": 'binary',
                                                                  "idf": None,
                                                                  }), procs=8)

In [20]:
train_length = df_train.shape[0]
concat_text = pd.concat([df_train['comment_text'], df_test['comment_text']])
X_text = wb.fit_transform(concat_text)

Normalize text
Extract wordbags

In [21]:
X_train = X_text[:train_length]
X_test = X_text[train_length:]

In [29]:
from sklearn.cross_validation import train_test_split
import lightgbm as lgbm
X_train, X_valid, y_train, y_valid = train_test_split(X_train, df_train.iloc[:, 2:], test_size=0.1, random_state=13)

In [34]:
lgb_train = lgbm.Dataset(X_train, y_train.iloc[:, 0])
lgb_eval = lgbm.Dataset(X_valid, y_valid.iloc[:, 0], reference=lgb_train)

In [36]:
from sklearn.linear_model import RidgeClassifier

In [37]:
model = RidgeClassifier(alpha=5.0, fit_intercept=True, copy_X=True, tol=0.001, solver='auto', random_state=138)
%time model.fit(X_train, y_train.iloc[:, 0])
%time print( np.sqrt( np.mean( (model.predict(X_valid) - y_valid.iloc[:, 0] )**2 ) ) )

CPU times: user 1min 23s, sys: 132 ms, total: 1min 24s
Wall time: 1min 24s
0.2318752598
CPU times: user 4 ms, sys: 3.17 ms, total: 7.17 ms
Wall time: 29.2 ms